image: rocker/r-devel:latest
before_script:
    - cat /etc/apt/sources.list
    - apt-get update && apt-get upgrade -y && apt-get -y install libssl-dev libxml2-dev
    - R --vanilla -e 'install.packages("desc", repos = "https://cloud.r-project.org/")'
    - R --vanilla -e ' for (p in desc::desc_get_deps()[["package"]]) {if (! require(p, character.only = TRUE)) install.packages(p, repos = "https://cloud.r-project.org/")}'
    - R --vanilla -e 'print(sessionInfo())'

test:
  script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}"  --as-cran 
    - R --vanilla -e 'covr::package_coverage()'
    - # R --vanilla -e 'covr::package_coverage(token = 20f3e0cc90e248d6be7efc7417390536)'
