image: rocker/verse:latest
before_script:
    - cat /etc/apt/sources.list
    - apt-get update && apt-get upgrade -y && apt-get -y install libssl-dev libxml2-dev
    - R --vanilla -e 'install.packages("desc", repos = "https://cloud.r-project.org/")'
    - R --vanilla -e ' for (p in desc::desc_get_deps()[["package"]]) {if (! require(p, character.only = TRUE)) install.packages(p, repos = "https://cloud.r-project.org/")}'
    - R --vanilla -e 'print(sessionInfo())'

build:
  stage: build
  script:
    - R CMD build . --no-build-vignettes --no-manual
    
check:
  stage: test
  script:  R --vanilla -e 'rmdcheck::rcmdcheck(".")'

test:
  stage: test
  script: R --vanilla -e 'install.packages("covr", repos = "https://cloud.r-project.org/"); covr::package_coverage()'
  coverage: '/^.*\s*Coverage:\s*\d+.\d+\%$/'

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
