image: rocker/r-devel:latest
test:
  script:
    - R --vanilla -e 'install.packages("desc", repos = "https://cloud.r-project.org/")'
    - R --vanilla -e ' for (p in desc::desc_get_deps()[["package"]]) {if (! require(p, character.only = TRUE)) install.packages(p)}'
    - R --vanilla -e 'print(sessionInfo())'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran 
